namespace Tahil.Application.ClassSessions.Commands;

public record RefreshSessionsCommand : ICommand<Result<bool>>;

public class RefreshSessionsCommandHandler(IClassSessionRepository classSessionRepository, IApplicationContext applicationContext, IUnitOfWork unitOfWork) 
    : ICommandHandler<RefreshSessionsCommand, Result<bool>>
{
    public async Task<Result<bool>> Handle(RefreshSessionsCommand request, CancellationToken cancellationToken)
    {
        var addResult = await classSessionRepository.AddAutoGeneratedSessionAsync(applicationContext.UserName);

        if (addResult.IsSuccess)
        {
            var result = await unitOfWork.SaveChangesAsync(cancellationToken);
            return Result<bool>.Success(result);
        }

        return addResult;
    }
}