namespace Tahil.Domain.Repositories;

public interface IClassSessionRepository: IRepository<ClassSession>
{
    Task<Result<List<ClassSessionDto>>> GetClassSessionsAsync();
    Task<Result<bool>> AddAutoGeneratedSessionAsync(string userName);
    Task<bool> ExistsInTenantAsync(int? id, Guid? tenantId);
}