namespace Tahil.Domain.Repositories;

public interface IClassSessionRepository: IRepository<ClassSession>
{
    Task<Result<List<ClassSessionDto>>> GetClassSessionsAsync(SessionSearchCriteriaDto sessionSearchCriteria, Guid tenantId);
    Task<Result<bool>> AddAutoGeneratedSessionAsync(string userName);
    Task<Result<bool>> DeleteSessionAsync(int id, Guid tenantId);
    Task<bool> HasIncompleteAttendancesAsync(int sessionId, Guid tenantId);
    Task<bool> ExistsInTenantAsync(int id, Guid tenantId);
}